package br.edu.ufam.scfpcu.model;
// Generated Jan 13, 2014 5:46:24 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "scfpcu")
public class Usuario implements java.io.Serializable {

	private int idServidor;
	private Cargo cargo;
	private String siape;
	private String nome;
	private String email;
	private String login;
	private String senha;
	private Set<Veiculo> veiculos = new HashSet<Veiculo>(0);

	public Usuario() {
	}

	public Usuario(int idServidor, Cargo cargo, String siape, String nome,
			String email, String login, String senha) {
		this.idServidor = idServidor;
		this.cargo = cargo;
		this.siape = siape;
		this.nome = nome;
		this.email = email;
		this.login = login;
		this.senha = senha;
	}
	public Usuario(int idServidor, Cargo cargo, String siape, String nome,
			String email, String login, String senha, Set<Veiculo> veiculos) {
		this.idServidor = idServidor;
		this.cargo = cargo;
		this.siape = siape;
		this.nome = nome;
		this.email = email;
		this.login = login;
		this.senha = senha;
		this.veiculos = veiculos;
	}

	@Id
	@Column(name = "id_servidor", unique = true, nullable = false)
	public int getIdServidor() {
		return this.idServidor;
	}

	public void setIdServidor(int idServidor) {
		this.idServidor = idServidor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cargo", nullable = false)
	@NotNull
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@Column(name = "SIAPE", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getSiape() {
		return this.siape;
	}

	public void setSiape(String siape) {
		this.siape = siape;
	}

	@Column(name = "Nome", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Email", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Login", nullable = false, length = 11)
	@NotNull
	@Length(max = 11)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "Senha", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Veiculo> getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Set<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

}
